import type { Metadata, Viewport } from "next";
import { Geist_Mono, Montserrat, Outfit } from "next/font/google";
import "./globals.css";
import { AppProviders } from "./providers";
import { MISSIONS_HERO_THEME_COLOR } from "@/lib/guest-missions-gradients";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  display: "swap",
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/** `viewport-fit=cover` lets backgrounds reach the notch / status bar; `env(safe-area-inset-*)` then pads content. */
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: MISSIONS_HERO_THEME_COLOR,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.variable}>
      <body
        className={`${montserrat.className} ${geistMono.variable} ${outfit.variable} antialiased`}
      >
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
